apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stg-track-my-case-service-dev
  namespace: stg-track-my-case-service-dev
  annotations:
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    external-dns.alpha.kubernetes.io/set-identifier: stg-track-my-case-service-dev-stg-track-my-case-service-dev-green
    meta.helm.sh/release-name: stg-track-my-case-service-dev
    meta.helm.sh/release-namespace: stg-track-my-case-service-dev
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Content-Type-Options: nosniff";
      more_set_headers "X-Frame-Options: deny";
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  ingressClassName: default
  rules:
  - host: stg-track-my-case-service-dev.apps.live.cloud-platform.service.justice.gov.uk
    http:
      paths:
      - backend:
          service:
            name: stg-track-my-case-service-dev
            port:
              number: 80
        path: /api
        pathType: Prefix
  tls:
  - hosts:
    - stg-track-my-case-service-dev.apps.live.cloud-platform.service.justice.gov.uk