apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    external-dns.alpha.kubernetes.io/set-identifier: probation-search-probation-search-dev-green
    ingress.kubernetes.io/whitelist-source-range: "35.176.126.163/32,35.178.162.73/32,52.56.195.113/32"
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: ingress-basic-auth
  name: probation-search
  namespace: hmpps-probation-search-dev
spec:
  ingressClassName: default
  rules:
    - host: probation-search-dev.hmpps.service.justice.gov.uk
      http:
        paths:
          - backend:
              service:
                name: es-proxy
                port:
                  number: 9200
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - probation-search-dev.hmpps.service.justice.gov.uk
      secretName: probation-search-cert
