apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  namespace: intranet-staging
  labels:
    prometheus: prometheus-operator
    role: alert-rules
    release: prometheus-operator
  name: monitoring-rules-intranet
spec:
  groups:
    - name: kubernetes-apps
      rules:
        - alert: KubeQuotaAlmostFull
          annotations:
            description: Namespace {{ $labels.namespace }} is using {{ $value | humanizePercentage }} of its {{ $labels.resource }} quota.
            runbook_url: https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubequotaalmostfull
            summary: Namespace quota is going to be full.
          expr: |
            kube_resourcequota{job="kube-state-metrics", type="used", namespace="intranet-staging"}
              / ignoring(instance, job, type)
            (kube_resourcequota{job="kube-state-metrics", type="hard", namespace="intranet-staging"} > 0)
              > 0.9 < 1
          for: 15m
          labels:
            severity: intranet-staging
        - alert: KubeQuota-Exceeded
          annotations:
            message: Namespace {{ $labels.namespace }} is using {{ printf "%0.0f" $value
              }}% of its {{ $labels.resource }} quota.
            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubequotaexceeded
          expr: |-
            100 * kube_resourcequota{job="kube-state-metrics", type="used", namespace="intranet-staging"} 
            / ignoring(instance, job, type)
            (kube_resourcequota{job="kube-state-metrics", type="hard", namespace="intranet-staging"} > 0)
            > 90
          for: 15m
          labels:
            severity: intranet-staging
        - alert: KubePodCrashLooping
          # pint file/disable alerts/template
          annotations:
            message: Pod {{ $labels.namespace }}/{{ $labels.pod }} ({{ $labels.container
              }}) is restarting {{ printf "%.2f" $value }} times / 5 minutes.
            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubepodcrashlooping
          expr: |-
            rate(kube_pod_container_status_restarts_total{job="kube-state-metrics", namespace="intranet-staging"}[5m]) * 60 > 0
          for: 5m
          labels:
            severity: intranet-staging
        - alert: KubePodNotReady
          annotations:
            message: Pod {{ $labels.namespace }}/{{ $labels.pod }} has been in a non-ready
              state for longer than 5 minutes.
            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubepodnotready
          expr: |-
            sum by (namespace, pod) (kube_pod_status_phase{job="kube-state-metrics", phase=~"Pending|Unknown", namespace="intranet-staging"}) 
            > 0
          for: 5m
          labels:
            severity: intranet-staging
        - alert: KubeDeploymentGenerationMismatch
          annotations:
            message: Deployment generation for {{ $labels.namespace }}/{{ $labels.deployment
              }} does not match, this indicates that the Deployment has failed but has
              not been rolled back.
            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubedeploymentgenerationmismatch
          expr: |-
            kube_deployment_status_observed_generation{job="kube-state-metrics", namespace="intranet-staging"}
            !=
            kube_deployment_metadata_generation{job="kube-state-metrics", namespace="intranet-staging"}
          for: 15m
          labels:
            severity: intranet-staging

    - name: application-rules
      rules:
      - alert: ServiceInsufficientAccessPolicy
        expr: http_status_code_wp_home{namespace="intranet-staging"} != 401
        for: 1m
        labels:
          severity: intranet-staging
        annotations:
          message: Namespace {{ $labels.namespace }} (homepage) is returning an unexpected status code {{ printf "%0.0f" $value}}.
          runbook_url: https://dsdmoj.atlassian.net/wiki/spaces/CDPT/pages/5124292758/Alerts+runbooks#ServiceInsufficientAccessPolicy
          dashboard_url: https://grafana.live.cloud-platform.service.justice.gov.uk/d/bdwyqxz07sxkwg/intranet-service?orgId=1&var-namespace=intranet-staging

      - alert: ServiceAbsentAccessPolicy
        expr: absent(http_status_code_wp_home{namespace="intranet-staging"}) == 1
        for: 1m
        labels:
          severity: intranet-staging
        annotations:
          message: Namespace {{ $labels.namespace }} (homepage) is not returning a status code.
          runbook_url: https://dsdmoj.atlassian.net/wiki/spaces/CDPT/pages/5124292758/Alerts+runbooks#ServiceAbsentAccessPolicy
          dashboard_url: https://grafana.live.cloud-platform.service.justice.gov.uk/d/bdwyqxz07sxkwg/intranet-service?orgId=1&var-namespace=intranet-staging

      - alert: ServiceInsufficientHeaderHandling
        expr: http_status_code_invalid_header{namespace="intranet-staging"} != 400
        for: 1m
        labels:
          severity: intranet-staging
        annotations:
          message: Namespace {{ $labels.namespace }} (invalid header) is returning an unexpected status code {{ printf "%0.0f" $value}}.
          runbook_url: https://dsdmoj.atlassian.net/wiki/spaces/CDPT/pages/5124292758/Alerts+runbooks#ServiceInsufficientHeaderHandling
          dashboard_url: https://grafana.live.cloud-platform.service.justice.gov.uk/d/bdwyqxz07sxkwg/intranet-service?orgId=1&var-namespace=intranet-staging

    - name: cronjob-alerts
      rules:
      - alert: WpCronJobStuck
        expr: |
          (
            time() - kube_cronjob_status_last_successful_time{
              cronjob="wp-cron-trigger",
              namespace="intranet-staging"
            }
          ) > 300
          AND ON() (7 <= hour() <= 21)
        for: 0s
        labels:
          severity: intranet-staging
        annotations:
          summary: "WordPress cron job hasn't run successfully in over 5 minutes"
          runbook_url: https://dsdmoj.atlassian.net/wiki/spaces/CDPT/pages/5124292758/Alerts+PHP+NodeJS+runbooks#WpCronJobStuck
