apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: helloworld-rubyapp-ingress
  namespace: ${namespace}
spec:
  tls:
  - hosts:
    - ${namespace}.apps.${hostname}
  rules:
  - host: ${namespace}.apps.${hostname}
    http:
      paths:
      - path: /
        backend:
          serviceName: rubyapp-service
          servicePort: 4567
