apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-ops
  namespace: kube-ops
  labels:
    application: kube-ops
    business-unit: cloud-platform
    cluster: cloud-platform-test-1
    contact_email: oliver.anwyll@digital.justice.gov.uk
    environment: test
    github_team: WebOps
    is-production: no
    namespace: kube-ops
    owner: cloud-platform
    source_code_url: "https://github.com/ministryofjustice/cloud-platform-environments/"
    version: v0.8.1
spec:
  replicas: 1
  selector:
    matchLabels:
      application: kube-ops
  template:
    metadata:
      labels:
        application: kube-ops
        version: v0.8.1
    spec:
      serviceAccount: kube-ops
      containers:
      - name: service
        # see https://github.com/hjacobs/kube-ops-view/releases
        image: hjacobs/kube-ops-view:0.8.1
        env:
          - name: APP_URL
            value: "https://kube-ops.apps.cloud-platform-test-1.k8s.integration.dsd.io/redirect_uri"
          - name: AUTHORIZE_URL
            value: "https://moj-cloud-platforms-dev.eu.auth0.com/authorize"
          - name: ACCESS_TOKEN_URL
            value: "https://moj-cloud-platforms-dev.eu.auth0.com/oauth/token"
          - name: CREDENTIALS_DIR
            value: "/etc/secrets"
        args:
        # remove this option to use built-in memory store
        - --redis-url=redis://kube-ops-redis:6379
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 50Mi
        volumeMounts:
        - name: auth-secrets
          mountPath: "/etc/secrets"
          readOnly: true
      volumes:
      - name: auth-secrets
        secret:
          secretName: kube-ops-oidc

