apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: offender-events-prod
    prometheus: cloud-platform
  name: dps-prometheus-rules-sqs
  namespace: offender-events-prod
spec:
  groups:
  - name: DPS-SQS-SNS
    rules:
    - alert: SQS-oldest-message
      annotations:
        message: SQS - {{ $labels.queue_name }} has message older than 15mins, check consumers are healthy
        runbook_url: https://dsdmoj.atlassian.net/wiki/spaces/NOM/pages/1739325587/DPS+Runbook
        dashboard_url: https://grafana.live.cloud-platform.service.justice.gov.uk/d/AWSSQS000/aws-sqs?orgId=1&var-datasource=Cloudwatch&var-region=default&var-queue={{ $labels.queue_name }}&from=now-6h&to=now
      expr: |-
        sum(aws_sqs_approximate_age_of_oldest_message_maximum{
          queue_name!~"Digital-Prison-Services-prod-(hmpps_)?prisoner_(to|from)_nomis_.+|Digital-Prison-Services-prod-prisoner_offender_search_queue|Digital-Prison-Services-prod-prisoner_offender_search_domain_queue|Digital-Prison-Services-prod-hmpps_domain_event_logger_queue",
          queue_name!~"Digital-Prison-Services-prod-hmpps_workload_offender_events_queue|Digital-Prison-Services-prod-hmpps_allocation_required|Digital-Prison-Services-prod-hmpps_tier_calculation_allocation|Digital-Prison-Services-prod-hmpps_allocations_offender_events_queue|Digital-Prison-Services-prod-workload_prisoner_hmpps_queue",
          queue_name!="Digital-Prison-Services-prod-prison_to_probation_update_mirror.*",
          queue_name!~"Digital-Prison-Services-prod-hmpps_tier.*",
          queue_name!="Digital-Prison-Services-prod-cfo_queue",
          queue_name!="Digital-Prison-Services-prod-in_cell_hmpps_queue",
          queue_name!="Digital-Prison-Services-prod-probation_offender_search_event_dl_queue",
          queue_name!~"Digital-Prison-Services-prod-prison_to_probation_update.*",
          queue_name!="Digital-Prison-Services-prod-pic_probation_offender_events_queue",
          queue_name=~"Digital-Prison-Services-prod.*",
          queue_name!~".*_dl|.*dlq|.*_dl_queue"
        } offset 5m) by (queue_name) > 15 * 60
      for: 10m
      labels:
        severity: digital-prison-service

    - alert: SQS-number-of-messages
      annotations:
        message: SQS - {{ $labels.queue_name }} - number of messages={{ $value }} (exceeds 100), check consumers are healthy
        runbook_url: https://dsdmoj.atlassian.net/wiki/spaces/NOM/pages/1739325587/DPS+Runbook
        dashboard_url: https://grafana.live.cloud-platform.service.justice.gov.uk/d/AWSSQS000/aws-sqs?orgId=1&var-datasource=Cloudwatch&var-region=default&var-queue={{ $labels.queue_name }}&from=now-6h&to=now
      expr: |-
        sum(aws_sqs_approximate_number_of_messages_visible_maximum{
          queue_name!~"Digital-Prison-Services-prod-(hmpps_)?prisoner_(to|from)_nomis_.+|Digital-Prison-Services-prod-prisoner_offender_search_queue|Digital-Prison-Services-prod-hmpps_domain_event_logger_queue",
          queue_name!~"Digital-Prison-Services-prod-hmpps_workload_offender_events_queue|Digital-Prison-Services-prod-hmpps_allocation_required|Digital-Prison-Services-prod-hmpps_tier_calculation_allocation|Digital-Prison-Services-prod-hmpps_allocations_offender_events_queue|Digital-Prison-Services-prod-workload_prisoner_hmpps_queue",
          queue_name!~"Digital-Prison-Services-prod-hmpps_tier.*",
          queue_name!="Digital-Prison-Services-prod-cfo_queue",
          queue_name!="Digital-Prison-Services-prod-in_cell_hmpps_queue",
          queue_name!="Digital-Prison-Services-prod-probation_offender_search_event_dl_queue|Digital-Prison-Services-prod-probation_offender_search_event_queue|Digital-Prison-Services-prod-prison_to_probation_update_mirror_hmpps_queue",
          queue_name!="Digital-Prison-Services-prod-pic_probation_offender_events_queue",
          queue_name!~"Digital-Prison-Services-prod-prison_to_probation_update.*",
          queue_name=~"Digital-Prison-Services-prod.*",
          queue_name!~".*_dl|.*dlq|.*_dl_queue"
        } offset 5m) by (queue_name) > 100
      for: 10m
      labels:
        severity: digital-prison-service

    # - alert: SQS-oldest-message-CFO
    #   annotations:
    #     message: SQS - {{ $labels.queue_name }} has message older than 15mins, check consumers are healthy.  https://grafana.live.cloud-platform.service.justice.gov.uk/d/AWSSQS000/aws-sqs?orgId=1&var-datasource=Cloudwatch&var-region=default&var-queue={{ $labels.queue_name }}&from=now-6h&to=now
    #   expr: |-
    #     sum(aws_sqs_approximate_age_of_oldest_message_maximum{queue_name="Digital-Prison-Services-prod-cfo_queue", queue_name!~".*_dl"} offset 5m) by (queue_name) > 15 * 60
    #   for: 10m
    #   labels:
    #     severity: hmpps-cfo-dms
    # - alert: SQS-number-of-messages-CFO
    #   annotations:
    #     message: SQS - {{ $labels.queue_name }} - number of messages={{ $value }} (exceeds 100), check consumers are healthy.  https://grafana.live.cloud-platform.service.justice.gov.uk/d/AWSSQS000/aws-sqs?orgId=1&var-datasource=Cloudwatch&var-region=default&var-queue={{ $labels.queue_name }}&from=now-6h&to=now
    #   expr: |-
    #     sum(aws_sqs_approximate_number_of_messages_visible_maximum{queue_name="Digital-Prison-Services-prod-cfo_queue", queue_name!~".*_dl"} offset 5m) by (queue_name) > 100
    #   for: 10m
    #   labels:
    #     severity: hmpps-cfo-dms

    - alert: SNS-no-messages-published-prison
      annotations:
        message: "SNS topic for Prison Offender Events - {{ $labels.topic_name }} - no messages published in last 20 mins, check offender-events app is healthy"
        runbook_url: https://dsdmoj.atlassian.net/wiki/spaces/NOM/pages/1739325587/DPS+Runbook
        dashboard_url: https://grafana.live.cloud-platform.service.justice.gov.uk/d/AWSSNS000/dps-aws-sns?orgId=1&var-topic={{ $labels.topic_name }}&from=now-6h&to=now
      expr: |-
        absent(aws_sns_number_of_messages_published_sum{topic_name=~"cloud-platform-Digital-Prison-Services-160f3.*"} offset 5m) == 1
      for: 20m
      labels:
        severity: digital-prison-service

    - alert: SNS-no-messages-published-probation
      annotations:
        message: "SNS topic for Probation Offender Events - {{ $labels.topic_name }} - no messages published in last 20 mins, check offender-events app is healthy"
        runbook_url: https://dsdmoj.atlassian.net/wiki/spaces/NOM/pages/1739325587/DPS+Runbook
        dashboard_url: https://grafana.live.cloud-platform.service.justice.gov.uk/d/AWSSNS000/dps-aws-sns?orgId=1&var-topic={{ $labels.topic_name }}&from=now-6h&to=now
      expr: |-
        (absent(aws_sns_number_of_messages_published_sum{topic_name=~"cloud-platform-Digital-Prison-Services-c2d99.*"} offset 5m) == 1) and ((day_of_week() >= 1 and day_of_week() <= 5) and (hour() >= 8 and hour() <= 17))
      for: 30m
      labels:
        severity: probation-integration-notifications

    - alert: SQS-events-dlq-not-empty
      annotations:
        message: SQS Deadletter queue - {{ $labels.queue_name }} has {{ $value }} messages
        runbook_url: https://dsdmoj.atlassian.net/wiki/spaces/NOM/pages/1739325587/DPS+Runbook
        dashboard_url: https://grafana.live.cloud-platform.service.justice.gov.uk/d/AWSSQS000/aws-sqs?orgId=1&var-datasource=Cloudwatch&var-region=default&var-queue={{ $labels.queue_name }}&from=now-6h&to=now
      expr: |-
        sum(aws_sqs_approximate_number_of_messages_visible_maximum{
          queue_name!~"Digital-Prison-Services-prod-(hmpps_)?prisoner_(to|from)_nomis_.+|Digital-Prison-Services-prod-prisoner_offender_search_domain_dlq|Digital-Prison-Services-prod-prisoner_offender_search_queue_dl|dps-prod-prisoner_offender_index_queue_dl|Digital-Prison-Services-prod-hmpps_domain_event_logger_dlq",
          queue_name!~"Digital-Prison-Services-prod-hmpps_workload_offender_events_queue_dl|Digital-Prison-Services-prod-hmpps_allocation_required_dlq|Digital-Prison-Services-prod-hmpps_tier_calculation_allocation_dlq|Digital-Prison-Services-prod-hmpps_allocations_offender_events_queue_dl|Digital-Prison-Services-prod-workload_prisoner_hmpps_dlq",
          queue_name!~"Digital-Prison-Services-prod-hmpps_tier.*_dl.*",
          queue_name!="Digital-Prison-Services-prod-probation_offender_search_event_dl_queue",
          queue_name!="Digital-Prison-Services-prod-pic_probation_offender_events_queue_dl",
          queue_name!~"Digital-Prison-Services-prod-prison_to_probation_update.*",
          queue_name=~"Digital-Prison-Services-prod-.*_dl.*|dps-prod-.*_dl.*"
        } offset 5m) by (queue_name) > 0
      for: 10m
      labels:
        severity: digital-prison-service

    - alert: SQS-events-dlq-not-empty
      annotations:
        message: SQS Deadletter queue - {{ $labels.queue_name }} has {{ $value }} messages
        runbook_url: https://dsdmoj.atlassian.net/wiki/spaces/NOM/pages/1739325587/DPS+Runbook
        dashboard_url: https://grafana.live.cloud-platform.service.justice.gov.uk/d/AWSSQS000/aws-sqs?orgId=1&var-datasource=Cloudwatch&var-region=default&var-queue={{ $labels.queue_name }}&from=now-6h&to=now
      expr: |-
        sum(aws_sqs_approximate_number_of_messages_visible_maximum{
          queue_name=~"Digital-Prison-Services-prod-prison_to_probation_update_queue_dl"
        } offset 5m) by (queue_name) > 0
      for: 10m
      labels:
        severity: probation-integration-notifications
