apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: offender-events-prod
    prometheus: cloud-platform
  name: dps-prometheus-rules-sqs
  namespace: offender-events-prod
spec:
  groups:
  - name: DPS-SQS-SNS
    rules:
    - alert: SQS-oldest-message
      annotations:
        message: SQS - {{ $labels.queue_name }} has message older than 15mins, check consumers are healthy.  https://grafana.cloud-platform.service.justice.gov.uk/d/AWSSQS000/aws-sqs?orgId=1&var-datasource=Cloudwatch&var-region=default&var-queue={{ $labels.queue_name }}&from=now-6h&to=now
        runbook_url: https://dsdmoj.atlassian.net/wiki/spaces/NOM/pages/1739325587/DPS+Runbook
      expr: |-
        sum(aws_sqs_approximate_age_of_oldest_message_maximum{queue_name!="Digital-Prison-Services-prod-cfo_queue",queue_name=~"Digital-Prison-Services-prod.*", queue_name!~".*_dl"}) by (queue_name) > 15 * 60
      for: 10m
      labels:
        severity: digital-prison-service
    - alert: SQS-number-of-messages
      annotations:
        message: SQS - {{ $labels.queue_name }} - number of messages={{ $value }} (exceeds 100), check consumers are healthy.  https://grafana.cloud-platform.service.justice.gov.uk/d/AWSSQS000/aws-sqs?orgId=1&var-datasource=Cloudwatch&var-region=default&var-queue={{ $labels.queue_name }}&from=now-6h&to=now
        runbook_url: https://dsdmoj.atlassian.net/wiki/spaces/NOM/pages/1739325587/DPS+Runbook
      expr: |-
        sum(aws_sqs_approximate_number_of_messages_visible_maximum{queue_name!="Digital-Prison-Services-prod-cfo_queue",queue_name=~"Digital-Prison-Services-prod.*", queue_name!~".*_dl"}) by (queue_name) > 100
      for: 10m
      labels:
        severity: digital-prison-service
    - alert: SQS-oldest-message-CFO
      annotations:
        message: SQS - {{ $labels.queue_name }} has message older than 15mins, check consumers are healthy.  https://grafana.cloud-platform.service.justice.gov.uk/d/AWSSQS000/aws-sqs?orgId=1&var-datasource=Cloudwatch&var-region=default&var-queue={{ $labels.queue_name }}&from=now-6h&to=now
      expr: |-
        sum(aws_sqs_approximate_age_of_oldest_message_maximum{queue_name="Digital-Prison-Services-prod-cfo_queue", queue_name!~".*_dl"}) by (queue_name) > 15 * 60
      for: 10m
      labels:
        severity: hmpps-cfo-dms
    - alert: SQS-number-of-messages-CFO
      annotations:
        message: SQS - {{ $labels.queue_name }} - number of messages={{ $value }} (exceeds 100), check consumers are healthy.  https://grafana.cloud-platform.service.justice.gov.uk/d/AWSSQS000/aws-sqs?orgId=1&var-datasource=Cloudwatch&var-region=default&var-queue={{ $labels.queue_name }}&from=now-6h&to=now
      expr: |-
        sum(aws_sqs_approximate_number_of_messages_visible_maximum{queue_name="Digital-Prison-Services-prod-cfo_queue", queue_name!~".*_dl"}) by (queue_name) > 100
      for: 10m
      labels:
        severity: hmpps-cfo-dms
    - alert: SNS-no-messages-published-prison
      annotations:
        message: "SNS topic for Prison Offender Events - {{ $labels.topic_name }} - no messages published in last 20 mins, check offender-events app is healthy. https://grafana.cloud-platform.service.justice.gov.uk/d/AWSSNS000/dps-aws-sns?orgId=1&var-topic={{ $labels.topic_name }}&from=now-6h&to=now"
        runbook_url: https://dsdmoj.atlassian.net/wiki/spaces/NOM/pages/1739325587/DPS+Runbook
      expr: |-
        absent(aws_sns_number_of_messages_published_sum{topic_name=~"cloud-platform-Digital-Prison-Services-160f3.*"}) == 1
      for: 20m
      labels:
        severity: digital-prison-service
    - alert: SNS-no-messages-published-probation
      annotations:
        message: "SNS topic for Probation Offender Events - {{ $labels.topic_name }} - no messages published in last 20 mins, check offender-events app is healthy. https://grafana.cloud-platform.service.justice.gov.uk/d/AWSSNS000/dps-aws-sns?orgId=1&var-topic={{ $labels.topic_name }}&from=now-6h&to=now"
        runbook_url: https://dsdmoj.atlassian.net/wiki/spaces/NOM/pages/1739325587/DPS+Runbook
      expr: |-
        (absent(aws_sns_number_of_messages_published_sum{topic_name=~"cloud-platform-Digital-Prison-Services-c2d99.*"}) == 1) and ((day_of_week() >= 1 and day_of_week() <= 5) and (hour() >= 8 and hour() <= 17))
      for: 30m
      labels:
        severity: digital-prison-service
    - alert: SQS-probation-events-dlq-not-empty
      annotations:
        message: SQS - {{ $labels.queue_name }} has message(s) older than 15m
        runbook_url: https://dsdmoj.atlassian.net/wiki/spaces/NOM/pages/1739325587/DPS+Runbook
      expr: |-
        sum by(queue_name) (aws_sqs_approximate_number_of_messages_visible_maximum{queue_name=~"Digital-Prison-Services-dev-probation_offender_search_event_dl_queue|dps-dev-probation_offender_search_index_dl_queue"}) > 0
      for: 15m
      labels:
        severity: digital-prison-service

