apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    role: alert-rules
  name: prometheus-custom-rules-hmpps-allocations
  namespace: workforce-management-prod
spec:
  groups:
    - name: application-rules
      rules:
        - alert: SQS-oldest-message
          annotations:
            message: SQS - {{ $labels.queue_name }} has message older than 15mins, check consumers are healthy.  https://grafana.live.cloud-platform.service.justice.gov.uk/d/AWSSQS000/aws-sqs?orgId=1&var-datasource=Cloudwatch&var-region=default&var-queue={{ $labels.queue_name }}&from=now-6h&to=now
            runbook_url: https://dsdmoj.atlassian.net/wiki/spaces/MaS/pages/3775856869/Allocations+runbook
          expr: |-
            sum(aws_sqs_approximate_age_of_oldest_message_maximum{queue_name=~"Digital-Prison-Services-prod-hmpps_allocation_required|Digital-Prison-Services-prod-hmpps_tier_calculation_allocation|Digital-Prison-Services-prod-hmpps_allocations_offender_events_queue"} offset 5m) by (queue_name) > 15 * 60
          for: 10m
          labels:
            severity: hmpps-tier
        - alert: SQS-events-dlq-not-empty
          annotations:
            message: SQS Deadletter queue - {{ $labels.queue_name }} has {{ $value }} messages
            runbook_url: https://dsdmoj.atlassian.net/wiki/spaces/MaS/pages/3775856869/Allocations+runbook
          expr: |-
            sum(aws_sqs_approximate_number_of_messages_visible_maximum{queue_name=~"Digital-Prison-Services-prod-hmpps_allocation_required_dlq|Digital-Prison-Services-prod-hmpps_tier_calculation_allocation_dlq|Digital-Prison-Services-prod-hmpps_allocations_offender_events_queue_dl"} offset 5m) by (queue_name) > 0
          for: 10m
          labels:
            severity: hmpps-tier
