apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-rubyapp
  namespace: cp-dummy-gitops-dev
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: helloworld-rubyapp
    spec:
      containers:
      - name: rubyapp
        image: ministryofjustice/cloud-platform-helloworld-ruby
        ports:
        - containerPort: 4567
