apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  namespace: laa-court-data-ui-dev
  labels:
    prometheus: cloud-platform
    role: alert-rules
  name: prometheus-custom-rules-laa-court-data-ui
spec:
  groups:
  - name: application-rules
    rules:
    - alert: Instance-Down
      expr: absent(up{namespace="laa-court-data-ui-dev"}) == 1
      for: 1m
      labels:
        severity: laa-court-get-paid
    - alert: Quota-Exceeded
      expr: 100 * kube_resourcequota{job="kube-state-metrics",type="used",namespace="laa-court-data-ui-dev"} / ignoring(instance, job, type) (kube_resourcequota{job="kube-state-metrics",type="hard",namespace="laa-court-data-ui-dev"} > 0) > 90
      for: 1m
      labels:
        severity: laa-court-get-paid
      annotations:
        message: laa-court-data-ui-dev is using {{ printf "%0.0f" $value}}% of its {{ $labels.resource }} quota.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubequotaexceeded
    - alert: NotFound-Threshold-Reached
      expr: sum(rate(ruby_http_requests_total{status="404", namespace="laa-court-data-ui-dev"}[86400s])) * 86400 > 100
      for: 1m
      labels:
        severity: laa-court-get-paid
      annotations:
        message: laa-court-data-ui-dev More than a hundred 404 errors in one day
        runbook_url: https://kibana.cloud-platform.service.justice.gov.uk/_plugin/kibana/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-24h,mode:quick,to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:ec9109a0-2b35-11e9-ac82-95e56bd45b02,key:kubernetes.namespace_name,negate:!f,params:(query:laa-court-data-ui-dev,type:phrase),type:phrase,value:laa-court-data-ui-dev),query:(match:(kubernetes.namespace_name:(query:laa-court-data-ui-dev,type:phrase))))),index:ec9109a0-2b35-11e9-ac82-95e56bd45b02,interval:auto,query:(language:lucene,query:'log:%22RoutingError%22'),sort:!('@timestamp',desc))
    - alert: nginx-5xx-error
      expr: sum(rate(nginx_ingress_controller_requests{exported_namespace="laa-court-data-ui-dev", status=~"5.."}[5m])) * 300 > 5
      for: 1m
      labels:
        severity: laa-court-get-paid
      annotations:
        message: laa-court-data-ui-dev An HTTP 5xx error has occurred
        runbook_url: https://kibana.cloud-platform.service.justice.gov.uk/_plugin/kibana/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-24h,to:now))&_a=(columns:!(log_processed.status,log_processed.http_referer,log_processed.request_uri),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'71644ed0-d648-11ea-b6f0-6bf964cd13a4',key:log_processed.kubernetes_namespace,negate:!f,params:(query:laa-court-data-ui-dev),type:phrase,value:laa-court-data-ui-dev),query:(match:(log_processed.kubernetes_namespace:(query:laa-court-data-ui-dev,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'71644ed0-d648-11ea-b6f0-6bf964cd13a4',key:log_processed.status,negate:!f,params:(query:'500'),type:phrase,value:'500'),query:(match:(log_processed.status:(query:'500',type:phrase))))),index:'71644ed0-d648-11ea-b6f0-6bf964cd13a4',interval:auto,query:(language:lucene,query:''),sort:!(!('@timestamp',desc)))
    - alert: DiskSpace-Threshold-Reached
      expr: container_fs_usage_bytes{namespace="laa-court-data-ui-dev"} / 1024 / 1024 > 150 or absent(container_fs_usage_bytes{namespace="laa-court-data-ui-dev"})
      for: 1m
      labels:
        severity: laa-court-get-paid
      annotations:
        message: laa-court-data-ui-dev Container disk space usage is more than 150Mb or is not reported
    - alert: Long-Request
      expr: ruby_http_duration_seconds{namespace="laa-court-data-ui-dev"} > 30
      for: 1m
      labels:
        severity: laa-court-get-paid
      annotations:
        message: laa-court-data-ui-dev Request is taking more than 30 seconds
