# Default values for podinfo.

replicaCount: 2
logLevel: info

ingress:
  enabled: true
  className: ${ingress_class}
  annotations: 
    nginx.ingress.kubernetes.io/custom-http-errors: "404"
    external-dns.alpha.kubernetes.io/set-identifier: ${external_dns}
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    nginx.ingress.kubernetes.io/server-snippet: location = /metrics { deny all; }
  path: /
  hosts: 
    - host: ${host_name}
      paths:
      - path: /
        pathType: ImplementationSpecific
  tls:
    - secretName:
      hosts:
        - ${host_name}

resources:
  limits:
    cpu: 100m
    memory: 100Mi
  requests:
    cpu: 40m
    memory: 16Mi
