apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: how-out-of-date-are-we-app-ingress
  namespace: how-out-of-date-are-we
  annotations:
    kubernetes.io/ingress.class: "nginx"
    external-dns.alpha.kubernetes.io/aws-weight: "0"
    external-dns.alpha.kubernetes.io/set-identifier: how-out-of-date-are-we-app-ingress-how-out-of-date-are-we-blue
spec:
  tls:
  - hosts:
    - how-out-of-date-are-we.apps.live-1.cloud-platform.service.justice.gov.uk
  rules:
    - host: how-out-of-date-are-we.apps.live-1.cloud-platform.service.justice.gov.uk
      http:
        paths:
        - path: /
          backend:
            serviceName: how-out-of-date-are-we-service
            servicePort: 4567
