apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  namespace: laa-data-claims-event-service-prod
  labels:
    prometheus: cloud-platform
    role: alert-rules
  name: prometheus-custom-rules-laa-data-claims-event-service-prod
spec:
  groups:
  - name: application-rules
    rules:
    - alert: NamespaceDown
      expr: absent(up{namespace="laa-data-claims-event-service-prod"}) == 1
      for: 1m
      labels:
        severity: laa-data-claims-event-service-prod
      annotations:
        message: Namespace laa-data-claims-event-service-prod is down.
        runbook_url: https://dsdmoj.atlassian.net/wiki/spaces/WHCZA/pages/5829263558/Runbook+Data+Claims
        dashboard_url: https://grafana.live.cloud-platform.service.justice.gov.uk/d/laa-d-perf-s-api-prod-a-claims-api/a080904?orgId=1&from=now-15m&to=now&timezone=browser&var-helmInstall=laa&var-helmInstallClaimEventService=prod&var-helmInstallClaimUI=prod

    - alert: KubeLowPodCount
      expr: sum (kube_pod_status_phase{namespace="laa-data-claims-event-service-prod", phase="Running"}) < 1
      labels:
        severity: laa-data-claims-event-service-prod
      annotations:
        message: Namespace laa-data-claims-event-service-prod has fewer than expected number of running pods.
        runbook_url: https://dsdmoj.atlassian.net/wiki/spaces/WHCZA/pages/5829263558/Runbook+Data+Claims
        dashboard_url: https://grafana.live.cloud-platform.service.justice.gov.uk/d/laa-d-perf-s-api-prod-a-claims-api/a080904?orgId=1&from=now-15m&to=now&timezone=browser&var-helmInstall=laa&var-helmInstallClaimEventService=prod&var-helmInstallClaimUI=prod

    - alert: KubeQuotaExceeded
      expr: 100 * kube_resourcequota{job="kube-state-metrics",type="used",namespace="laa-data-claims-event-service-prod"} / ignoring(instance, job, type) (kube_resourcequota{job="kube-state-metrics",type="hard",namespace="laa-data-claims-event-service-prod"} > 0) > 90
      for: 1m
      labels:
        severity: laa-data-claims-event-service-prod
      annotations:
        message: Namespace laa-data-claims-event-service-prod is using more than 90% of its allocated resources.
        runbook_url: https://dsdmoj.atlassian.net/wiki/spaces/WHCZA/pages/5829263558/Runbook+Data+Claims
        dashboard_url: https://grafana.live.cloud-platform.service.justice.gov.uk/d/laa-d-perf-s-api-prod-a-claims-api/a080904?orgId=1&from=now-15m&to=now&timezone=browser&var-helmInstall=laa&var-helmInstallClaimEventService=prod&var-helmInstallClaimUI=prod

    - alert: SubmissionErrorDetected
      expr: |-
        sum(increase(claims_event_service_submissions_with_errors_total{namespace="laa-data-claims-event-service-prod"}[5m])) > 50
      for: 1m
      labels:
        severity: laa-data-claims-event-service-prod
      annotations:
        message: More than 50 submission errors in the last 5 minutes in laa-data-claims-event-service-prod. Check the logs for details.
        runbook_url: https://dsdmoj.atlassian.net/wiki/spaces/WHCZA/pages/5829263558/Runbook+Data+Claims
        dashboard_url: https://grafana.live.cloud-platform.service.justice.gov.uk/d/laa-d-perf-s-api-prod-a-claims-api/a080904?orgId=1&from=now-15m&to=now&timezone=browser&var-helmInstall=laa&var-helmInstallClaimEventService=prod&var-helmInstallClaimUI=prod
