apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    role: alert-rules
  name: prometheus-custom-rules-hmpps-workload
  namespace: hmpps-workload-prod
spec:
  groups:
    - name: application-rules
      rules:
        - alert: SQS-oldest-message
          annotations:
            message: SQS - manage-a-workforce-production-hmpps_workload_s3_extract_event_queue has message older than 2 mins, check consumers are healthy.  https://grafana.live-1.cloud-platform.service.justice.gov.uk/d/AWSSQS000/aws-sqs?orgId=1&var-datasource=Cloudwatch&var-region=default&var-queue=manage-a-workforce-production-hmpps_workload_s3_extract_event_queue&from=now-6h&to=now
            runbook_url: https://dsdmoj.atlassian.net/wiki/spaces/MaS/pages/3533964702/WMT+Run+book
          expr: |-
            sum(aws_sqs_approximate_age_of_oldest_message_maximum{queue_name="Digital-Prison-Services-prod-hmpps_workload_offender_events_queue|manage-a-workforce-production-hmpps_workload_s3_extract_event_queue"} offset 1m) by (queue_name) > 2 * 60
          for: 10m
          labels:
            severity: hmpps-tier
        - alert: SQS-number-of-messages
          annotations:
            message: SQS - manage-a-workforce-production-hmpps_workload_s3_extract_event_queue - number of messages={{ $value }} (exceeds 2), check consumers are healthy.  https://grafana.live-1.cloud-platform.service.justice.gov.uk/d/AWSSQS000/aws-sqs?orgId=1&var-datasource=Cloudwatch&var-region=default&var-queue=manage-a-workforce-production-hmpps_workload_s3_extract_event_queue&from=now-6h&to=now
            runbook_url: https://dsdmoj.atlassian.net/wiki/spaces/MaS/pages/3533964702/WMT+Run+book
          expr: |-
            sum(aws_sqs_approximate_number_of_messages_visible_maximum{queue_name="Digital-Prison-Services-prod-hmpps_workload_offender_events_queue|manage-a-workforce-production-hmpps_workload_s3_extract_event_queue"} offset 1m) by (queue_name) > 2
          for: 10m
          labels:
            severity: hmpps-tier
        - alert: SQS-events-dlq-not-empty
          annotations:
            message: SQS Deadletter queue - manage-a-workforce-production-hmpps_workload_s3_extract_event_dlq has {{ $value }} messages
            runbook_url: https://dsdmoj.atlassian.net/wiki/spaces/MaS/pages/3533964702/WMT+Run+book
          expr: |-
            sum(aws_sqs_approximate_number_of_messages_visible_maximum{queue_name=~"Digital-Prison-Services-prod-hmpps_workload_offender_events_queue_dl|manage-a-workforce-production-hmpps_workload_s3_extract_event_dlq"} offset 1m) by (queue_name) > 0
          for: 10m
          labels:
            severity: hmpps-tier
