name: devsec

# on:
#   schedule:
#     - cron: '0 * * * *'

on:
  push:
    branches: [ tfsec-improvements ]
  pull_request:
  workflow_dispatch:

jobs:
  devsec:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - uses: aquasecurity/tfsec-sarif-action@v0.1.4
        with:
          tfsec_args: --force-all-dirs --soft-fail -m=HIGH -e=github-repositories-private,github-branch_protections-require_signed_commits,github-actions-no-plain-text-action-secrets,aws-iam-no-policy-wildcards,aws-ecr-enforce-immutable-repository,aws-rds-enable-performance-insights-encryption,aws-s3-encryption-customer-key,aws-sqs-enable-queue-encryption
          sarif_file: tfsec.sarif
      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: tfsec.sarif